from abc import ABC, abstractmethod
from typing import Any


class BackendClient(ABC):
    @abstractmethod
    def post(self, path: str, body: dict, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def get(self, path: str, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def put(self, path: str, body: dict, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def delete(self, path: str, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def post_slot(self, data: dict, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def list_slots(self, params: dict, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def update_slot(self, uuid: str, data: dict, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def delete_slot(self, uuid: str, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def list_medicineres(self, params: dict, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def create_mediciner(self, data: dict, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def get_mediciner(self, uuid: str, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def update_mediciner(self, uuid: str, data: dict, headers: dict) -> tuple[dict, int]: ...

    @abstractmethod
    def lookup_crm(self, state: str, number: str, headers: dict) -> tuple[dict, int]: ...
